### ISSUE TITLE
Stereo mode?

### ISSUE THREAD

**Issue by em00k** [b3dgs/sc68#1]
## Expected Behavior
Most actual players allow you to switch between mono / stereo. 
A left B centre C right 
A left C centre B right 
mono

## Actual Behavior
Currently mono can sound distorted. 

## Steps to Reproduce the Problem

  1. Test any song. 

## Specifications

  - OS:
 Rasp Pi

**Comment by DjThunder** [comment]
Did you try with:
`void sc68Config(int interpolation, int stereo_join); // stereo_join to true`

Working fine with Lionheart Remake project.
